import { TextDecoder } from "node:util";

import type { NormalizedPlugin, NormalizedSkill } from "./types.js";
import { qualifySlug, toSlug } from "./util.js";

export interface GenerateOptions {
  model?: string;
  connectorExtension: string;
  connectorAvailable: boolean;
  allowStaticConnections: boolean;
}

export interface GeneratedPlugin {
  files: Map<string, string>;
  warnings: string[];
}

const generatedHeader = "// Generated by eve-openai-plugins. Edit the access policy, not this file.\n";

function serializeBytes(bytes: Uint8Array): string {
  try {
    const value = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    if (Buffer.from(value, "utf8").equals(Buffer.from(bytes))) return JSON.stringify(value);
  } catch {
    // Binary skill assets remain byte-for-byte via base64.
  }
  return `Buffer.from(${JSON.stringify(Buffer.from(bytes).toString("base64"))}, "base64")`;
}

function definitionBody(skill: NormalizedSkill): string {
  const fields = [
    `description: ${JSON.stringify(skill.description)}`,
    `markdown: ${JSON.stringify(skill.markdown)}`,
  ];
  if (skill.license) fields.push(`license: ${JSON.stringify(skill.license)}`);
  if (skill.metadata) fields.push(`metadata: ${JSON.stringify(skill.metadata)}`);
  const files = Object.entries(skill.files);
  if (files.length > 0) {
    fields.push(`files: {\n${files.map(([path, bytes]) => `      ${JSON.stringify(path)}: ${serializeBytes(bytes)}`).join(",\n")}\n    }`);
  }
  return `{\n    ${fields.join(",\n    ")}\n  }`;
}

function dynamicSkillSource(pluginId: string, capabilityId: string, skill: NormalizedSkill): string {
  return `${generatedHeader}import { Buffer } from "node:buffer";
import { defineDynamic, defineSkill } from "eve/skills";
import { isOpenAIPluginEnabled } from "../lib/openai-plugin-access.js";

const skill = defineSkill(${definitionBody(skill)});

export default defineDynamic({
  events: {
    "turn.started": async (_event, ctx) =>
      (await isOpenAIPluginEnabled(ctx, ${JSON.stringify({ pluginId, kind: "skill", id: capabilityId })}))
        ? skill
        : null,
  },
});
`;
}

function staticSkillSource(skill: NormalizedSkill): string {
  return `${generatedHeader}import { Buffer } from "node:buffer";
import { defineSkill } from "eve/skills";

export default defineSkill(${definitionBody(skill)});
`;
}

function commandAsSkill(plugin: NormalizedPlugin, command: NormalizedPlugin["commands"][number]): NormalizedSkill {
  const skillNames = new Map(plugin.skills.map((skill) => [skill.sourcePath.match(/skills\/([^/]+)/)?.[1], skill.id]));
  const rewritten = command.markdown
    .replace(
      /(?:\.\.\/)*skills\/([^/\s`]+)\/SKILL\.md/g,
      (original, name: string) => {
        const skill = skillNames.get(name);
        return skill
          ? `the Eve skill \"${qualifySlug(["openai-plugin", toSlug(plugin.manifest.name), skill])}\"`
          : original;
      },
    )
    .replaceAll("$ARGUMENTS", "the arguments supplied by the user for this command");
  return {
    id: `command-${command.id}`,
    sourcePath: command.sourcePath,
    description: `${command.description} Explicit-use command imported from /${plugin.manifest.name}:${command.id}.`,
    markdown: `# Imported command: /${plugin.manifest.name}:${command.id}\n\n${rewritten}`,
    files: {},
  };
}

function subagentSource(pluginId: string, agent: NormalizedPlugin["agents"][number], model: string): string {
  return `${generatedHeader}import { defineAgent, defineDynamic } from "eve";
import { isOpenAIPluginEnabled } from "../../lib/openai-plugin-access.js";

const agent = defineAgent({
  description: ${JSON.stringify(agent.description)},
  model: ${JSON.stringify(model)},
});

export default defineDynamic({
  events: {
    "turn.started": async (_event, ctx) =>
      (await isOpenAIPluginEnabled(ctx, ${JSON.stringify({ pluginId, kind: "subagent", id: agent.id })}))
        ? agent
        : null,
  },
});
`;
}

function connectionSource(description: string, url: string): string {
  return `${generatedHeader}import { defineMcpClientConnection } from "eve/connections";

export default defineMcpClientConnection({
  description: ${JSON.stringify(description)},
  url: ${JSON.stringify(url)},
});
`;
}

export function accessPolicySource(): string {
  return `import type { DynamicResolveContext } from "eve/tools";

/** A plugin capability being resolved for the active Eve principal. */
export interface OpenAIPluginCapability {
  readonly pluginId: string;
  readonly kind: "skill" | "subagent";
  readonly id: string;
}

/**
 * Central policy seam for imported OpenAI plugin capabilities.
 *
 * The default enables installed capabilities deployment-wide. Replace this
 * body with tenant, user, plan, or feature-flag checks over ctx.session.auth
 * and ctx.channel before serving an untrusted or restricted plugin.
 */
export function isOpenAIPluginEnabled(
  _ctx: DynamicResolveContext,
  _capability: OpenAIPluginCapability,
): boolean | Promise<boolean> {
  return true;
}

/**
 * Credential seam for ChatGPT apps used inside imported subagents.
 * Subagents do not inherit the root agent's configured extensions. Return the
 * active principal's workspace token here, using the same external secret
 * store as the root eve-openai-connectors mount. The safe default disables
 * connector tools in imported children.
 */
export function getOpenAIPluginConnectorToken(
  _ctx: Pick<DynamicResolveContext, "session">,
): string | null | Promise<string | null> {
  return null;
}
`;
}

export function generatePlugin(plugin: NormalizedPlugin, options: GenerateOptions): GeneratedPlugin {
  const files = new Map<string, string>();
  const warnings = [...plugin.warnings];
  const pluginId = toSlug(plugin.manifest.name);
  const rootPrefix = qualifySlug(["openai-plugin", pluginId]);
  const capabilities: NormalizedSkill[] = [
    ...plugin.skills,
    ...plugin.commands.map((command) => commandAsSkill(plugin, command)),
  ];
  if (plugin.apps.length > 0 && !options.connectorAvailable) {
    warnings.push(
      `Plugin ${plugin.manifest.name} needs ChatGPT apps. Install eve-openai-connectors and mount agent/extensions/${options.connectorExtension}.ts for the root agent.`,
    );
  }

  for (const skill of capabilities) {
    files.set(
      `agent/skills/${qualifySlug([rootPrefix, skill.id])}.ts`,
      dynamicSkillSource(pluginId, skill.id, skill),
    );
  }

  const model = options.model;
  if (plugin.agents.length > 0 && !model) {
    throw new Error(
      `Plugin ${plugin.manifest.name} contributes subagents. Pass --model or use a root agent.ts with a literal model string.`,
    );
  }

  for (const agent of plugin.agents) {
    if (!model) throw new Error("Imported subagent model was not resolved.");
    const child = `agent/subagents/${qualifySlug([rootPrefix, agent.id])}`;
    files.set(`${child}/agent.ts`, subagentSource(pluginId, agent, model));
    files.set(`${child}/instructions.md`, agent.instructions);
    for (const skill of capabilities) {
      files.set(`${child}/skills/${skill.id}.ts`, staticSkillSource(skill));
    }
    if (plugin.apps.length > 0) {
      files.set(
        `${child}/extensions/${options.connectorExtension}.ts`,
        `${generatedHeader}import openaiConnectors from "eve-openai-connectors";
import { getOpenAIPluginConnectorToken } from "../../../lib/openai-plugin-access.js";

export default openaiConnectors({
  getToken: getOpenAIPluginConnectorToken,
});
`,
      );
    }
  }

  if (plugin.mcpServers.length > 0) {
    if (!options.allowStaticConnections) {
      warnings.push(
        `Omitted ${plugin.mcpServers.length} unauthenticated HTTP MCP connection${plugin.mcpServers.length === 1 ? "" : "s"}; pass --allow-static-connections to install static Eve connections.`,
      );
    } else {
      for (const server of plugin.mcpServers) {
        files.set(
          `agent/connections/${qualifySlug([rootPrefix, server.id])}.ts`,
          connectionSource(server.description, server.url),
        );
        for (const agent of plugin.agents) {
          files.set(
            `agent/subagents/${qualifySlug([rootPrefix, agent.id])}/connections/${server.id}.ts`,
            connectionSource(server.description, server.url),
          );
        }
      }
      warnings.push(
        "Installed MCP connections are static Eve capabilities and are not hidden by openai-plugin-access.ts; enforce authorization in the connection or channel.",
      );
    }
  }

  return { files, warnings };
}
